# Firebase
apiKey = "AIzaSyBvePXiKVnyKXz_Rm4bxzNSrZWyNZfbgOI"
authDomain = "mindmate-301d7.firebaseapp.com"
projectId = "mindmate-301d7"
storageBucket = "mindmate-301d7.firebasestorage.app"
messagingSenderId = "245301281736"
appId = "1:245301281736:web:f8fe4ea44538a73910b6fd"
databaseURL = "https://mindmate-301d7-default-rtdb.firebaseio.com/"

# Gemini
google_api_key = "AIzaSyC4G_Q2Hi7fWFNFoIvsCtvYFjoZjjE0dz8"
