# Firebase
apiKey = "your-api-key"
authDomain = "auth-domain"
projectId = "your-project-id"
storageBucket = "storage-bucket"
messagingSenderId = "messaging-sender-id"
appId = "app-id"
databaseURL = "database-url"

# Gemini
google_api_key = "google-api-key"
